insert into ARCHCE.ENTITY_INTEREST
(
    NAME,
    BACKGROUND,
    PURPOSE,
    SCOPE,
    APPROACH,
    SCHEDULE,
    MILESTONES
)
values
(
    '“Me Deixe” System',
    '<p>The urgent need for an additional technological solution directly integrated with law enforcement agencies to combat and prevent violence against women in the state of Sergipe. </p>',
    '<p>To develop the &quot;Me Deixe&quot; System, a technological solution designed to address the needs of combating domestic violence in the semi-arid region of Sergipe, Brazil. Employing a multidisciplinary approach that integrates knowledge from information technology, human rights, and social work, the &quot;Me Deixe&quot; System aims to provide female victims of violence with an effective and accessible tool to seek help, protect their safety, and pursue justice. To develop a solution grounded in robust software architecture principles tailored for social technologies, prioritizing robustness, effectiveness, and accessibility.</p>',
    '<p>Initially, two applications will be needed: a mobile application for use by victims and a web application for use by the police. The mobile application with a basic interface for making calls and the web application for listing and managing emergency calls made by victims.</p>',
    '<ol><li><p>Evaluation and Selection:</p><ul><li>We will evaluate existing architecture frameworks (e.g., TOGAF, Zachman Framework) based on their suitability for the project&#39;s complexity and domain.</li><li>We will assess available architecture elaboration techniques (e.g., workshops, scenario modeling) and identify the most efficient methods for gathering requirements and defining the architecture.</li><li>We will review pre-defined architecture viewpoints, modeling templates, and view generation methods to ensure they capture the necessary information for stakeholders.</li><li>If existing options are not ideal, we will consider developing or modifying frameworks, templates, and methods to suit the project&#39;s specific needs. This should be done with justification and documented for future reference.</li></ul></li><li><p>Tailored Architecture Definition:</p><ul><li>The chosen framework will be used as a foundation, but we will have the flexibility to adapt it to the project&#39;s specific requirements.</li><li>We will select appropriate viewpoints (e.g., functional, data) to document the architecture from different perspectives, ensuring all stakeholders have a clear understanding.</li><li>We will leverage existing modeling templates or develop customized ones to capture the necessary details of the architecture components, their interactions, and data flows.</li><li>View generation methods will be chosen based on their effectiveness in communicating the architecture to different audiences (e.g., diagrams for technical teams, narrative descriptions for stakeholders).</li></ul></li><li><p>Documentation and Communication:</p><ul><li>The architecture will be comprehensively documented, including decisions made, justification for choices, and a clear traceability matrix linking requirements to architecture components.</li><li>We will utilize appropriate tools for documenting the architecture, potentially leveraging existing enterprise architecture tools or collaborative platforms depending on governance guidelines.</li><li>Effective communication strategies will be employed to present the architecture to stakeholders. This might involve workshops, presentations, and interactive visualizations to ensure understanding and buy-in.</li></ul></li><li><p>Continuous Improvement:</p><ul><li>We will adopt an iterative approach to architecture elaboration, allowing for refinements based on stakeholder feedback or changing project requirements.</li><li>The chosen architecture approach will be reviewed and assessed after project completion to identify areas for improvement for future projects.</li></ul></li></ol>',
    '<ul><li>Week 1-2: Requirements Analysis and Framework Selection (Milestone 1: Requirements Baseline)<ul><li>Activities:<ul><li>Analyze system requirements for functionality, performance, security, and scalability.</li><li>Identify key architectural drivers based on the requirements analysis.</li><li>Research and evaluate potential architecture frameworks and technologies that align with project goals, architecture governance, and available resources.</li></ul></li></ul></li><li>Week 3-4: High-Level Architecture Definition (Milestone 2: Initial Architecture Definition)<ul><li>Activities:<ul><li>Select the most suitable architecture framework based on the evaluation in Week 1-2.</li><li>Define the overall system architecture, including layers (e.g., presentation, business logic, data access) and communication protocols.</li><li>Identify major architectural components and their interactions.</li></ul></li></ul></li><li>Week 5-6: Technology Stack Selection and Integration Strategy (Milestone 3: Technology Stack Defined)<ul><li>Activities:<ul><li>Identify specific technologies (e.g., databases, programming languages) that align with the chosen framework and project requirements.</li><li>Define a strategy for integrating third-party APIs and external systems.</li><li>Consider infrastructure needs (e.g., cloud deployment) and security implications.</li></ul></li></ul></li><li>Week 7-8: Detailed Architecture Design and Refinement (Milestone 4: Detailed Architecture Defined)<ul><li>Activities:<ul><li>Refine the architecture based on selected technologies and identified integration points.</li><li>Design detailed component blueprints with interfaces, functionalities, and data flows.</li><li>Consider performance optimization strategies and potential scalability needs.</li></ul></li></ul></li><li>Week 9-10: Communication and Documentation (Milestone 5: Architecture Review and Sign-Off)<ul><li>Activities:<ul><li>Document the complete architecture, including decisions made, technologies chosen, and integration points.</li><li>Present the architecture to stakeholders for review and feedback.</li><li>Address any concerns and incorporate feedback into the final architecture documentation.</li></ul></li></ul></li></ul>',
    '<ul><li>Milestone 1: Requirements Baseline<ul><li>Deliverable: Documented set of system requirements, prioritized and categorized.</li></ul></li><li>Milestone 2: Initial Architecture Definition<ul><li>Deliverable: High-level architecture diagram with component descriptions, interactions, and chosen framework.</li></ul></li><li>Milestone 3: Technology Stack Defined<ul><li>Deliverable: Documented technology stack with justifications for selections and an integration strategy document.</li></ul></li><li>Milestone 4: Detailed Architecture Defined<ul><li>Deliverable: Detailed architecture documentation with component diagrams, specifications, and performance considerations.</li></ul></li><li>Milestone 5: Architecture Review and Sign-Off<ul><li>Deliverable: Finalized architecture documentation with stakeholder approvals.</li></ul></li></ul>'
);

insert into ARCHCE.ENTITY_INTEREST
(
    NAME,
    BACKGROUND,
    PURPOSE,
    SCOPE,
    APPROACH,
    SCHEDULE,
    MILESTONES
)
values
(
    'ArchCE Project',
    '<p>ArchCE (Architecture Conceptualization and Elaboration) functions as a web application. Users provide information about a specific entity, and ArchCE processes this input to generate various architectural work products, including models that visually represent the system''s structure and detailed descriptions that explain its functionalities.</p>',
    '<p>In contrast to most tools reviewed by \citeonline{IVANOV:2024}, which vary from basic diagramming tools to sophisticated documentation management systems, each offering distinct features and capabilities, ArchCE integrates some characteristics aligned with the developed process. Consequently, it adheres to the guidelines of ISO/IEC/IEEE 42020 and ISO/IEC/IEEE 42010.</p>',
    '<p>A first version will be developed using basic elements and without a expressive UI. Begins with the preparation of efforts (step 1), including the Architecture Elaboration Plan as a work product. This step is followed by the design of viewpoints (step 2), which includes the Architecture Viewpoint Report as a work product. The subsequent step is the development of views (step 3), which includes the Architecture Views Report as a work product. Finally, the assessment of the document (step 4) is undertaken, which includes the final work product, the Architecture Description.</p>',
    '<ol><li><p>Evaluation and Selection:</p><ul><li>We will evaluate existing architecture frameworks (e.g., TOGAF, Zachman Framework) based on their suitability for the project&#39;s complexity and domain.</li><li>We will assess available architecture elaboration techniques (e.g., workshops, scenario modeling) and identify the most efficient methods for gathering requirements and defining the architecture.</li><li>We will review pre-defined architecture viewpoints, modeling templates, and view generation methods to ensure they capture the necessary information for stakeholders.</li><li>If existing options are not ideal, we will consider developing or modifying frameworks, templates, and methods to suit the project&#39;s specific needs. This should be done with justification and documented for future reference.</li></ul></li><li><p>Tailored Architecture Definition:</p><ul><li>The chosen framework will be used as a foundation, but we will have the flexibility to adapt it to the project&#39;s specific requirements.</li><li>We will select appropriate viewpoints (e.g., functional, data) to document the architecture from different perspectives, ensuring all stakeholders have a clear understanding.</li><li>We will leverage existing modeling templates or develop customized ones to capture the necessary details of the architecture components, their interactions, and data flows.</li><li>View generation methods will be chosen based on their effectiveness in communicating the architecture to different audiences (e.g., diagrams for technical teams, narrative descriptions for stakeholders).</li></ul></li><li><p>Documentation and Communication:</p><ul><li>The architecture will be comprehensively documented, including decisions made, justification for choices, and a clear traceability matrix linking requirements to architecture components.</li><li>We will utilize appropriate tools for documenting the architecture, potentially leveraging existing enterprise architecture tools or collaborative platforms depending on governance guidelines.</li><li>Effective communication strategies will be employed to present the architecture to stakeholders. This might involve workshops, presentations, and interactive visualizations to ensure understanding and buy-in.</li></ul></li><li><p>Continuous Improvement:</p><ul><li>We will adopt an iterative approach to architecture elaboration, allowing for refinements based on stakeholder feedback or changing project requirements.</li><li>The chosen architecture approach will be reviewed and assessed after project completion to identify areas for improvement for future projects.</li></ul></li></ol>',
    '<ul><li>Week 1-2: Requirements Analysis and Framework Selection (Milestone 1: Requirements Baseline)<ul><li>Activities:<ul><li>Analyze system requirements for functionality, performance, security, and scalability.</li><li>Identify key architectural drivers based on the requirements analysis.</li><li>Research and evaluate potential architecture frameworks and technologies that align with project goals, architecture governance, and available resources.</li></ul></li></ul></li><li>Week 3-4: High-Level Architecture Definition (Milestone 2: Initial Architecture Definition)<ul><li>Activities:<ul><li>Select the most suitable architecture framework based on the evaluation in Week 1-2.</li><li>Define the overall system architecture, including layers (e.g., presentation, business logic, data access) and communication protocols.</li><li>Identify major architectural components and their interactions.</li></ul></li></ul></li><li>Week 5-6: Technology Stack Selection and Integration Strategy (Milestone 3: Technology Stack Defined)<ul><li>Activities:<ul><li>Identify specific technologies (e.g., databases, programming languages) that align with the chosen framework and project requirements.</li><li>Define a strategy for integrating third-party APIs and external systems.</li><li>Consider infrastructure needs (e.g., cloud deployment) and security implications.</li></ul></li></ul></li><li>Week 7-8: Detailed Architecture Design and Refinement (Milestone 4: Detailed Architecture Defined)<ul><li>Activities:<ul><li>Refine the architecture based on selected technologies and identified integration points.</li><li>Design detailed component blueprints with interfaces, functionalities, and data flows.</li><li>Consider performance optimization strategies and potential scalability needs.</li></ul></li></ul></li><li>Week 9-10: Communication and Documentation (Milestone 5: Architecture Review and Sign-Off)<ul><li>Activities:<ul><li>Document the complete architecture, including decisions made, technologies chosen, and integration points.</li><li>Present the architecture to stakeholders for review and feedback.</li><li>Address any concerns and incorporate feedback into the final architecture documentation.</li></ul></li></ul></li></ul>',
    '<ul><li>Milestone 1: Requirements Baseline<ul><li>Deliverable: Documented set of system requirements, prioritized and categorized.</li></ul></li><li>Milestone 2: Initial Architecture Definition<ul><li>Deliverable: High-level architecture diagram with component descriptions, interactions, and chosen framework.</li></ul></li><li>Milestone 3: Technology Stack Defined<ul><li>Deliverable: Documented technology stack with justifications for selections and an integration strategy document.</li></ul></li><li>Milestone 4: Detailed Architecture Defined<ul><li>Deliverable: Detailed architecture documentation with component diagrams, specifications, and performance considerations.</li></ul></li><li>Milestone 5: Architecture Review and Sign-Off<ul><li>Deliverable: Finalized architecture documentation with stakeholder approvals.</li></ul></li></ul>'
);